version: '3.1'
services:
  web:
    user: root
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./webdata:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=myodoo
    command: -d odoo_v16 -u library --dev=all
  db:
    user: root
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
  pgadmin:
      user: root
      image: dpage/pgadmin4:latest
      environment:
          PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
          PGADMIN_DEFAULT_PASSWORD: password
          PGADMIN_LISTEN_PORT: 80
      ports:
          - 15432:80
      volumes:
          - ./pgadmin:/var/lib/pgadmin
      depends_on:
          - db